# Generated by Django 5.2.4 on 2025-10-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_appointment_vehicle_alter_vehicle_user'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='appointment',
                    name='service_types',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='vehicle',
                ),
                migrations.RemoveField(
                    model_name='review',
                    name='appointment',
                ),
                migrations.RemoveField(
                    model_name='profile',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='vehicle',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='ServiceType',
                ),
                migrations.DeleteModel(
                    name='Appointment',
                ),
                migrations.DeleteModel(
                    name='Review',
                ),
                migrations.DeleteModel(
                    name='Profile',
                ),
                migrations.DeleteModel(
                    name='Vehicle',
                ),
            ],
        ),
    ]
