# Generated by Django 5.2.6 on 2025-10-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0009_remove_appointment_service_types_and_more'),
        ('core', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentClient',
            fields=[
            ],
            options={
                'permissions': [('access_appointment_page', 'Can access client appointment page')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.appointment',),
        ),
    ]
