# Generated by Django 5.2.6 on 2025-10-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_initial'),
        ('core', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClient',
            fields=[
            ],
            options={
                'permissions': [('access_profile_page', 'Can access client profile page')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.profile',),
        ),
        migrations.CreateModel(
            name='ReviewClient',
            fields=[
            ],
            options={
                'permissions': [('access_review_page', 'Can access client review page')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.review',),
        ),
        migrations.CreateModel(
            name='VehicleClient',
            fields=[
            ],
            options={
                'permissions': [('access_vehicle_page', 'Can access client vehicle page')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.vehicle',),
        ),
    ]
