# Generated by Django 5.2.6 on 2025-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_profileclient_reviewclient_vehicleclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_booking_page', 'Can access client booking page')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
