# Generated by Django 5.2.6 on 2025-10-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStaff',
            fields=[
            ],
            options={
                'permissions': [('access_appointment_page', 'Can access staff appointment page')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.appointment',),
        ),
    ]
