# Generated by Django 5.2.6 on 2025-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_phone_number'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_dashboard', 'Can access staff dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReviewStaff',
            fields=[
            ],
            options={
                'permissions': [('access_review_page', 'Can access staff review page')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.review',),
        ),
        migrations.CreateModel(
            name='VehicleStaff',
            fields=[
            ],
            options={
                'permissions': [('access_vehicle_page', 'Can access staff vehicle page')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.vehicle',),
        ),
    ]
